version: '3.9'
services:
  auth-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgres://auth_user:auth_pass@postgres:5432/auth_db
      - REDIS_URL=redis://redis:6379/0
      - ACCESS_TTL=15m
      - REFRESH_TTL=30d
      - PROVIDER_EMAIL=SMTP
      - PROVIDER_SMS=TWILIO
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - SMTP_FROM=auth@example.com
    depends_on:
      - postgres
      - redis
      - mail
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
volumes:
  pgdata:
